#!/usr/bin/env bash
# sync-skills.sh — Bidirectional skill sync between local ~/.claude/skills/ and vault
# Usage: sync-skills.sh [pull|push|sync|manifest]
#   pull     — vault -> local (get remote agent's changes)
#   push     — local -> vault (share this agent's changes)
#   sync     — pull then push (default)
#   manifest — regenerate SYNC.md only
#
# Designed for hook integration:
#   SessionStart -> pull (get latest from vault)
#   Stop         -> push (share local changes)
#
# Compatible with macOS bash 3.2 (no associative arrays)

set -eo pipefail

LOCAL_SKILLS="$HOME/.claude/skills"
VAULT_DIR="${ENGRAM_VAULT_DIR:-$HOME/Documents/vault}"
VAULT_SKILLS="$VAULT_DIR/Skills"
SYNC_MD="$VAULT_SKILLS/SYNC.md"
MODE="${1:-sync}"

# Platform classification
# Customize this for your setup — which skills are platform-specific?
get_platform() {
  case "$1" in
    # Example MAC-SPECIFIC skills (require macOS APIs)
    apple-*|macos-*|mail-app-*)
      echo "mac" ;;
    # Everything else is universal
    *)
      echo "universal" ;;
  esac
}

do_pull() {
  # Pull: vault -> local (get other agents' new/updated skills)
  if [ ! -d "$VAULT_SKILLS" ]; then
    return 0
  fi

  # Git pull vault first (fast-forward only)
  if [ -d "$VAULT_DIR/.git" ]; then
    git -C "$VAULT_DIR" pull --ff-only --quiet 2>/dev/null || true
  fi

  # rsync vault -> local (only newer files, preserve structure)
  rsync -a --update --exclude='SYNC.md' --exclude='.gitkeep' \
    "$VAULT_SKILLS/" "$LOCAL_SKILLS/" 2>/dev/null || true
}

do_push() {
  # Push: local -> vault (share this agent's changes)
  mkdir -p "$VAULT_SKILLS"

  # rsync local -> vault (only newer files, preserve structure)
  rsync -a --update --exclude='.DS_Store' --exclude='_archive/' \
    "$LOCAL_SKILLS/" "$VAULT_SKILLS/" 2>/dev/null || true

  # Generate manifest
  generate_manifest

  # Git commit + push if there are changes
  if [ -d "$VAULT_DIR/.git" ]; then
    cd "$VAULT_DIR"
    if ! git diff --quiet -- Skills/ 2>/dev/null || \
       [ -n "$(git ls-files --others --exclude-standard Skills/ 2>/dev/null)" ]; then
      git add Skills/ 2>/dev/null || true
      git commit -m "Sync skills from $(hostname -s)" --quiet 2>/dev/null || true
      git push --quiet 2>/dev/null || true
    fi
  fi
}

generate_manifest() {
  mkdir -p "$VAULT_SKILLS"

  cat > "$SYNC_MD" << 'HEADER'
# Skills Sync Manifest

Auto-generated by `sync-skills.sh`. Do not edit manually.

## Platform Legend
- **universal** — Works on any platform (Linux, macOS, etc.)
- **mac** — Requires macOS (AppleScript, Messages.db, Mail.app, etc.)

## Installing on a New Agent

```bash
# Copy skills from vault to local
rsync -a --exclude='SYNC.md' vault/Skills/ ~/.claude/skills/
```

## Skills

HEADER

  echo "| Skill | Platform | Files | Size | Last Modified |" >> "$SYNC_MD"
  echo "|-------|----------|-------|------|---------------|" >> "$SYNC_MD"

  for dir in "$VAULT_SKILLS"/*/; do
    [ -d "$dir" ] || continue
    skill_name=$(basename "$dir")
    platform=$(get_platform "$skill_name")
    file_count=$(find "$dir" -type f | wc -l | tr -d ' ')
    size=$(du -sh "$dir" 2>/dev/null | cut -f1 | tr -d ' ')
    last_mod=$(find "$dir" -type f -exec stat -f '%m' {} \; 2>/dev/null | sort -rn | head -1)
    if [ -n "$last_mod" ]; then
      last_mod_date=$(date -r "$last_mod" '+%Y-%m-%d' 2>/dev/null || echo "unknown")
    else
      last_mod_date="unknown"
    fi

    case "$platform" in
      mac) emoji="[mac]" ;;
      *) emoji="[all]" ;;
    esac

    echo "| ${emoji} ${skill_name} | ${platform} | ${file_count} | ${size} | ${last_mod_date} |" >> "$SYNC_MD"
  done

  echo "" >> "$SYNC_MD"
  echo "_Last synced: $(date '+%Y-%m-%d %H:%M:%S %Z') from $(hostname -s)_" >> "$SYNC_MD"
}

case "$MODE" in
  pull)
    do_pull
    ;;
  push)
    do_push
    ;;
  sync)
    do_pull
    do_push
    ;;
  manifest)
    generate_manifest
    ;;
  *)
    echo "Usage: sync-skills.sh [pull|push|sync|manifest]"
    exit 1
    ;;
esac
